### ISSUE TITLE
Published index.js file has CRLF line endings, breaks Linux

### ISSUE THREAD

**Issue by saboya** [charlesguse/run-script-os#1]
The current version of this package on npm is published with CRLF line endings, which causes this error on Linux:
```
/usr/bin/env: ‘node\r’: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! nw-demo@0.0.1 appendnw: `run-script-os`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nw-demo@0.0.1 appendnw script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/saboya/.npm/_logs/2017-07-03T11_25_44_222Z-debug.log
```

**Comment by wesbos** [comment]
@charlesguse I used this package in my video course and there are a handful of people getting this error - any way you can merge this?

**Comment by charlesguse** [comment]
Apologies for the delay. @saboya @wesbos I updated to 1.0.3 and converted the few CRLF files to LF.

**Comment by wesbos** [comment]
Thank you :)

**Comment by wesbos** [comment]
@charlesguse Can you publish to npm?

**Comment by charlesguse** [comment]
@wesbos yep! I just did. You should see the new one now.

**Comment by wesbos** [comment]
you're the best!

**Comment by ghost** [comment]
This issue is back again with 1.1.0.
1.0.7 works though.
