### ISSUE TITLE
Travis CI does not play nice with line 16, says .includes is not a function

### ISSUE THREAD

**Issue by BrenekH** [charlesguse/run-script-os#14]
Travis is not liking the .includes function as detailed in this [build log](https://travis-ci.com/zPaw/kotlin-for-frc/jobs/173243171). My suggestion is to wrap line 16 in a try catch to just accept process.platform if the line fails. 

I would do it myself but I can't reproduce with out pushing the version on to npm and then trying on Travis.

**Comment by zPaw** [comment]
Figured out a way to store a modified version as a tarball to test on Travis. Will try tomorrow.

**Comment by BrenekH** [comment]
Fixed the issue. Node needed to be updated.
For those interested, adding nvm install node to the before_install section of .travis.yml will fix it.
