### ISSUE TITLE
Doesn't support recursive yarn script call

### ISSUE THREAD

**Issue by silkPK** [charlesguse/run-script-os#16]
Script failed with a recursive yarn call:

package.json:
[...]
  "scripts": {
    "build": "yarn wsrun build --stages",
    "clean": "run-script-os",
    "clean:win32": "rmdir /S /Q .\\node_modules",
    "clean:darwin:linux": "rm -rf ./node_modules",
    "rebuild": "yarn clean && yarn",
},
[...]

Calling "yarn rebuild" run-script-os return error:

$ yarn clean && yarn
$ run-script-os
npm ERR! missing script: rebuild:linux
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     rebuild

**Comment by mathiscode** [comment]
This is somewhat related to #15, but in this case this is what I would do:

```json
"scripts": {
  "build": "yarn wsrun build --stages",
  "clean": "run-script-os",
  "clean:win32": "rmdir /S /Q .\node_modules",
  "clean:darwin:linux": "rm -rf ./node_modules",
  "rebuild": "yarn clean && yarn",
  "rebuild:win32:darwin:linux": "cd ."
} 
```

This allows run-script-os to run something successfully, but `cd .` is essentially a cross-platform no-op.

In PR #19, I've added the ability to use the `:default` alias as discussed in #3:

```json
"rebuild:default": "cd ."
```

The :default alias won't be available until @charlesguse merges the PR though.

**Comment by charlesguse** [comment]
I assume this isn't an issue anymore? Please reopen it if it's still an issue. Thanks
