### ISSUE TITLE
'babel' is not recognized

### ISSUE THREAD

**Issue by joebochill** [charlesguse/run-script-os#18]
I'm having an issue with combining babel with run-script-os. The script I'm trying to execute is supposed to build a sibling/dependency project, e.g.:
```
"build:dep":"run-script-os",
"build:dep:win32": "cd ../other-project && yarn build",
"build:dep:linux:darwin": "cd ../other-project && sudo yarn build",
```
and the build script for the dependency looks like:
```
"build": "yarn && babel src --presets @babel/preset-react,@babel/preset-env --out-dir dist"
```
I'm testing on Windows 10 at the moment. Running ```yarn build:dep:win32``` directly runs perfectly fine. But when I try to run ```yarn build:dep``` it fails with 'babel is not recognized as an internal or external command.' Ran it with npm/yarn and both have the same results.

Any ideas?

**Comment by mathiscode** [comment]
@joebochill I just tested this out and it worked for me. Does your dependency have @babel/cli as a devDependency?

Can you share your dependency's package.json?

**Comment by joebochill** [comment]
Can confirm this is working for me now. I just stood up a [minimum reproduction](https://github.com/joebochill/run-script-os-test) and it appears to be working fine on Mac and windows. It must've been something off in the particular project i was using it in.

For reference, the package.json for the dependency in the example looks like: 
```
{
    "name": "dependency",
    "version": "1.0.0",
    "description": "components that the main project depends on",
    "main": "./dist/index.js",
    "scripts": {
      "build": "yarn && babel src --presets @babel/preset-react,@babel/preset-env --out-dir dist"
    },
    "dependencies": {},
    "devDependencies": {
      "@babel/cli": "^7.0.0",
      "@babel/core": "^7.0.0",
      "@babel/preset-env": "^7.1.6",
      "@babel/preset-react": "^7.0.0",
      "babel-jest": "^24.0.0",
      "babel-polyfill": "^6.26.0",
      "react": "^16.8.6",
      "react-dom": "^16.8.6"
    },
    "peerDependencies": {
      "react": "^16.8.6",
      "react-dom": "^16.8.6"
    },
    "author": "joebochill"
}
```

and in the main project it's:
```
{
  "name": "main",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "build:dep":"run-script-os",
    "build:dep:win32": "cd ../dependency && yarn build",
    "build:dep:linux:darwin": "cd ../dependency && sudo yarn build"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "run-script-os": "^1.0.5"
  }
}
```
Thanks for taking a look @mathiscode - I'll go ahead and close this issue since it appears to be working properly.
