### ISSUE TITLE
Specify script name

### ISSUE THREAD

**Issue by jasekiw** [charlesguse/run-script-os#22]
This package uses a simple approach of getting the script name based on the arguments of the npm command. That does not work in all cases. (ex prepare called by install) I propose an argument to be added to allow users to specify the scripts to get around this issue. 

This repo seems pretty dead. If I make a PR will it be considered?

**Comment by charlesguse** [comment]
The repo isn't dead! I am just slow to response sometimes 😄 

Can you create a simple package.json that shows the bug in action? If you fix it, I would certainly consider adding it to the repo!

**Comment by jasekiw** [comment]
I created an example of the issue here:

https://github.com/jasekiw/run-scrip-os-bug-example

I then realized that I think my issue is the same as

https://github.com/charlesguse/run-script-os/issues/20


which currently has PR open that fixes that

https://github.com/charlesguse/run-script-os/pull/21


Is there a reason that PR hasn't been merged yet?

**Comment by charlesguse** [comment]
I believe this should be fixed now in 1.1.0. Please reopen it if it's still an issue. Thanks
