### ISSUE TITLE
Does not work with `npm i`

### ISSUE THREAD

**Issue by clubajax** [charlesguse/run-script-os#25]
I was installing my dependencies with `npm i` and suddenly things stopped working and dependencies were missing.

Turned out when I ran `npm install` it worked.

I tracked the problem down to line 30:

```
if (process.env.npm_config_user_agent.includes('yarn') && !options[1]) options[1] = 'install';
let osCommand = `${options[1]}:${platform}`;
```
I would get an error:

```
npm ERR! missing script: i:darwin
```

Which I assume is to be `install:darwin`

**Comment by kawatzaki** [comment]
Let's try to bring this issue to https://github.com/kawatzaki/run-script-os

I'll be fixing it so it's available in the @dr.amaton/run-script-os package, which is a temporary package I made that has a couple of issues solved.

**Comment by kawatzaki** [comment]
Weird, I tried to reproduce this error and wasn't able to on my package. Can you try it out and tell me what you got?

**Comment by charlesguse** [comment]
I assume this isn't an issue anymore? Please reopen it if it's still an issue. Thanks
