### ISSUE TITLE
use npm_lifecycle_event instead?

### ISSUE THREAD

**Issue by mo22** [charlesguse/run-script-os#26]
I want to use prepare:win32 and prepare:default and added prepare: "run-script-os" to my package.json - however it tries to run install:xxx as prepare is called from npm install.
When adding the following code it works fine:
```
if (process.env.npm_config_user_agent.includes('yarn') && !options[1]) options[1] = 'install';

// added this:
options[1] = process.env['npm_lifecycle_event'];

let osCommand = `${options[1]}:${platform}`;
```

**Comment by kawatzaki** [comment]
Hi,

You might wanna check out this forked package:
https://www.npmjs.com/package/@dr.amaton/run-script-os

More details on the repo:
https://github.com/kawatzaki/dr.amaton-run-script-os

**Comment by charlesguse** [comment]
I assume this isn't an issue anymore? Please reopen it if it's still an issue. Thanks

**Comment by mo22** [comment]
At first glance it looks good, thank you!
