### ISSUE TITLE
run-script-os does not work on yarn 2

### ISSUE THREAD

**Issue by cskeogh** [charlesguse/run-script-os#36]
run-script-os does not work on yarn 2.

```bash
$ yarn start
This is meant to be run from within npm script. See https://github.com/charlesguse/run-script-os
```

Perhaps related to issue #34

**Comment by charlesguse** [comment]
Can you please show how you are using run-script-os in your package.json?

**Comment by cskeogh** [comment]
Upgraded to 1.1.6 and now works. Thank you!
