### ISSUE TITLE
Propagate exit code

### ISSUE THREAD

**Issue by turpault** [charlesguse/run-script-os#4]
When the platform-specific script fails, it usually ends with a non-zero exit code. run-script-os hides those failures. In order to be really isomorphic, exit codes should be propagated when the script exits.

**Comment by charlesguse** [comment]
Good call! I will look into it this weekend.

**Comment by UselessPickles** [comment]
It appears that this may be as simple as adding the following code to the end of index.js:

```js
platformSpecific.on("exit", (code) => {
    process.exit(code);
});
```

I tried this and it seems to work, but I'm not confident enough with NodeJS to say this is the solution and create a PR.

**Comment by charlesguse** [comment]
The weekend of May 23rd.... or months from later...

Sorry about how slow I was at getting this merged in. Thanks for the suggestion @turpault , you were absolutely right to want the exit code to propagate. Thank you @UselessPickles for the code snippet. And thanks to @samstagern took the time to make a PR for it.

I added some test small manual tests in the package.json and have confirmed it works for Linux and Windows.

I appreciate all of your input into this and want to apologize for my slowness in responding to all this. Thanks everyone!
