### ISSUE TITLE
Some Error: "This is meant to be run from within npm script. See https://github.com/charlesguse/run-script-os"

### ISSUE THREAD

**Issue by ankopein** [charlesguse/run-script-os#42]
I tried to use run-script-os with npm 7.6.1, and 7.5.6 but it results in not starting the correct npm script and instead prints the message 
> "This is meant to be run from within npm script. See https://github.com/charlesguse/run-script-os" 

to std-out.

It works as expected with npm 6.14.11.

I'm on windows if that matters and my package.json:
```
 "build": "run-script-os",
    "build:darwin:linux": "npm run clean && tsc index.ts && node index.js && rm index.js",
    "build:win32": "del /Q .\\out && ts-node index.ts",
    "build:default": "echo 'This will run on any platform that does not have its own script'",
```
I call npm using `npm run build` from a Java process using [ProcessBuilder](https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html).

Is it somehow possible to use run-script-os using npm v7 ? It does not say anything about versions or the error in the README.md.

Thanks.

**Comment by jasontk19** [comment]
I seem to get this same issue when running Node `15.11.0` but not on earlier versions (tried 14 and 12) where it works fine.

**Comment by jasontk19** [comment]
Updating to the latest version of this package seemed to fix it for me:

` "run-script-os": "^1.1.5"`

**Comment by ankopein** [comment]
You're totally right! I still had 1.1.4.
Thanks @jasontk19 , didn't notice the new version.

**Comment by lionelmalletpro** [comment]
I had the same problem with Node v14.17.1 (on Windows 10)
it was run-script-os@1.0.7 => error "This is meant to be run from within npm script"
after updating to run-script-os@1.1.6 => NO MORE ERROR
