### ISSUE TITLE
Extras : tags

### ISSUE THREAD

**Issue by FireController1847** [charlesguse/run-script-os#5]
It'd be nice if I could do something like this:
```json
    "build:php": "run-script-os",
    "build:php:win32": "cpy **/*.php ../dist/ --parents --cwd=src/",
    "build:php:darwin:linux": "cd src; cp -vrf **/*.php ../dist --parents",
```

**Comment by mathiscode** [comment]
I just tested this and it worked as expected. Since your comment is nearly a year old, I'm assuming you already found a workaround though. 😅

**Comment by FireController1847** [comment]
@mathiscode Yeah quite frankly I have no idea what I was even doing lol
