### ISSUE TITLE
Yarn

### ISSUE THREAD

**Issue by mikecann** [charlesguse/run-script-os#9]
Doesnt work with yarn for some reason 😢 

```
yarn run v1.9.4
$ run-script-os
module.js:549
    throw err;
    ^

Error: Cannot find module '\c\dev\bam\user-domain\package.json'
    at Function...
```

**Comment by mathiscode** [comment]
@mikecann I'm not able to reproduce this issue with Yarn 1.16.0.

Can you try again with the latest version?

**Comment by charlesguse** [comment]
I assume this isn't an issue anymore? Please reopen it if it's still an issue. Thanks
